### ISSUE TITLE
Speedtest return HTTP Status 204 No Content

### ISSUE THREAD

**Issue by televisi** [maxandersen/internet-monitoring#26]
Hi,

When I went to [prometheus target page](http://localhost:9090/targets), the speedtest shows ```server returned HTTP status 204 No Content```

When I checked speed-test exporter log, this error is showing:
```
_speedTest:error Error: No server found, verify your proxy/network
    at gotServers (/home/node_modules/speedtest-net/index.js:621:25)
    at /home/node_modules/speedtest-net/index.js:107:16
    at /home/node_modules/speedtest-net/index.js:301:7
    at Parser.<anonymous> (/home/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:180:13)
    at SAXParser.onclosetag (/home/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/home/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/node_modules/sax/lib/sax.js:1436:13)
``` 

I was able to ping 8.8.8.8 from within the speed-test exporter container

Could someone please provide a solution to this?

Thank you

**Comment by 9M2PJU** [comment]
this is abandon project
